services:
  orders-db:
    # build: ./orders-service
    image: mysql:9.3
    env_file:
      - ./orders-service/.env
    ports:
      - "3306:3306"
    volumes:
      - ./orders-service/mysqldata:/var/lib/mysql
      - ./orders-service/mysqlinit:/docker-entrypoint-initdb.d


  products-db:
    # build: ./products-service
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./products-service/mongodbdata:/data/db
      - ./products-service/mongoinit:/docker-entrypoint-initdb.d
    env_file:
      - ./products-service/.env

  users-db:
    # build: ./users-service
    image: postgres:17
    env_file:
      - ./users-service/.env
    ports:
      - "5432:5432"
    volumes:
      - ./users-service/pgdata:/var/lib/postgresql/data
      - ./users-service/pginit:/docker-entrypoint-initdb.d
