services:
  orders-db:
    image: mysql:9.3
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysqlinit:/docker-entrypoint-initdb.d

  orders-service:
    build: .
    env_file:
      - .env
    environment:
      MYSQL_HOST: "orders-db"
      USERS_SERVICE_URL: "http://users-service:8000/users/"
      PRODUCTS_SERVICE_URL: "http://products-service:8000/products/"
    ports:
      - "8000:8000"
    depends_on:
      - orders-db