apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: orders-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: MYSQL_HOST
          value: "host.docker.internal"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "ordersdb"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "Pa55w0rd"
        - name: USERS_SERVICE_URL
          value: "http://users-service:8000/users/"
        - name: PRODUCTS_SERVICE_URL
          value: "http://products-service:8000/products/"
